### ISSUE TITLE
Prefer `id` for unique selectors

### ISSUE THREAD

**Issue by Conrad2134** [prashantswami/eslint-plugin-test-id#9]
There are a number of cases where having a unique `id` on an HTML element can be beneficial or downright necessary for accessibility. In general, it's a best-practice to include `id` on elements that you might want to link to (header elements) and interactive elements (form controls).

In these cases where we already have a unique `id` on an element, it shouldn't be necessary to include `data-test-id` (since we can reliably select the element by `id` instead). My main concern is driving the right behavior - we should make sure that we're including `id` when necessary and not relying on a `data-` attribute to identity those elements. This plugin wouldn't necessarily force you to include an `id`, but if you already had it, you just wouldn't hit this rule. Secondary, extra `data-` attributes do add some bloat to the code / bundle. If there are places where we don't need them, it would be great to not have to include them. Kent C. Dodds [also suggests](https://kentcdodds.com/blog/making-your-ui-tests-resilient-to-change#whats-with-the-data-testid-query) only using a "test id" attribute when other options are exhausted (in his case, Testing Library queries, but that advice can apply to any method of selecting).

My proposal is to add some logic to the plugin to ignore elements that already have an `id` attribute/prop, and not require `data-test-id` on those. Curious how others feel about this - let me know your thoughts!

**Comment by prashantswami** [comment]
Thanks for the suggestion @Conrad2134, Would this be helpful if this plugin automatically picks the value of `id` and adds it to `data-test-id`?

**Comment by Conrad2134** [comment]
In this case, `data-test-id` wouldn't be required if `id` was present, since `id` should always be unique.

**Comment by prashantswami** [comment]
@Conrad2134 can we close this? as we decided to keep `data-test-id` in all the cases.
